---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rocketchat-config
  namespace: rocketchat
data:
  MONGO_URL: mongodb://root:i7RhV6UwL9M@mg-service.mongodb:27018/rocketchat?authSource=admin
  USE_NATIVE_OPLOG: 'true'
  #MONGO_OPLOG_URL: mongodb://zjw:ilovejw@mg-service.mongodb:27018/rocketchat?authSource=admin
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: rocketchat-secret
#   namespace: rocketchat
# data:
#   MONGO_INITDB_ROOT_PASSWORD: aWxvdmVqdw==
# type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: rocketchat-service
  namespace: rocketchat
spec:
  selector:
    app: rocketchat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat-deployment
  namespace: rocketchat
  labels:
    app: rocketchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat
  template:
    metadata:
      labels:
        app: rocketchat
    spec:
      containers:
      - name: rocketchat
        image:  rocket.chat:latest
        envFrom:
          - configMapRef: 
              name: rocketchat-config
          # - secretRef:
          #     name: rocketchat-secret
        ports:
        - containerPort: 3000

